### ISSUE TITLE
Clarify documentation

### ISSUE THREAD

**Issue by andrewperry** [fwalzel/handlebars-i18n-cli#1]
What a fantastic project this is, and handlebars-i18n, which I hope to use and support.

I am not an experienced node developer, and am having difficulties getting the expected outcome following your instructions on my ARM macOS (Ventura 13.0.1).

For example:

```
mkdir cli-test
cd cli-test
npm i handlebars-i18n-cli
i18n-collect examples/templates/*.html examples/generated/translations.json --lng=de,fr,en
```

returns an error message of:

```
zsh: command not found: i18n-collect
```

What is the missing step so that the i18n-collect command is recognised by the cli?

**Comment by andrewperry** [comment]
FYI I also got the same result with:

```
git clone git@github.com:collaboratory-int/handlebars-i18n-cli.git
cd handlebars-i18n-cli
npm i handlebars-i18n-cli
i18n-collect examples/templates/*.html examples/generated/translations.json --lng=de,fr,en
```

**Comment by fwalzel** [comment]
Thank you for the appreciation and your reporting. I also get this error now on my laptop which runs a more recent MacOS then the one I developed the module on. My first guess is that zsh is now the common shell on Macs but the module was developed still in the realm of bin/bash. But I need to research on this error. What you could try in the meantime is if you can change your shell to bin bash and see if this works. Run `chsh -s /bin/bash` in a Terminal Window to switch your shell from Zsh to Bash, then restart your Terminal. New terminal windows will open using Bash. Alternatively (and just for the moment being, of course) you could cd in to *node_modules/handlebars-i18n-cli* and prompt `npm run i18n-collect ../examples/templates/sample-template.html ../examples/generated/my.json -- -lng=de,fr,en`. This command is specified in the package.json scripts. Note the double dash ' -- ' before the argument(s).

**Comment by andrewperry** [comment]
Thanks very much for the work around - don't really want to switch back to bash as I should probably learn my way around zsh. I just had to make sure I had created the examples/generated/ directory and away it went!

Thanks for all your work and for such a quick response!

**Comment by fwalzel** [comment]
Good to hear that it worked for you. For curiosity's sake: after you created examples/generated/ only the work around did it, right? Or did the whole `zsh: command not found: i18n-collect` go away? Because I would very much like that the CLI eventually runs under zsh just as it does in bash  ...

**Comment by andrewperry** [comment]
You are right - I still had to run it within the node_modules/handlebars-i18n-cli directory

**Comment by fwalzel** [comment]
I found out, that the error `zsh: command not found: i18n-collect` is prompted when the module misses linking. To fix this, you can run in your shell:

```bash
cd node_modules/handlebars-i18n-cli
sudo npm link
```

After this the command ` i18n-collect` should be generally available outside the handlebars-i18n-cli folder. I also added this info to the documentation of version 1.0.1
